apiVersion: v2
name: klicker-uzh-v3
description: A Helm chart for the KlickerUZH
type: application
version: 3.0.0-alpha.1
appVersion: v3.0.0-alpha.1
dependencies:
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
