releases:
  - name: klicker-v2-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: ../charts/klicker-uzh-v2
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values.yaml
      - appSecret: '{{ requiredEnv "APP_SECRET" }}'

        frontendPWA:
          replicaCount: 3
          image:
            tag: v2.0.0-alpha.42

        frontendManage:
          replicaCount: 1
          image:
            tag: v2.0.0-alpha.42

        backendGraphql:
          replicaCount: 3
          image:
            tag: v2.0.0-alpha.42

          apiDomain: '{{ requiredEnv "API_DOMAIN" }}'
          cookieDomain: '{{ requiredEnv "COOKIE_DOMAIN" }}'
          databaseUrl: '{{ requiredEnv "DATABASE_URL" }}'
          hiveToken: '{{ requiredEnv "HIVE_TOKEN" }}'

          redisCache:
            host: '{{ requiredEnv "REDIS_CACHE_HOST" }}'
            port: '{{ requiredEnv "REDIS_CACHE_PORT" }}'
            tls: '{{ requiredEnv "REDIS_CACHE_TLS" }}'
            pass: '{{ requiredEnv "REDIS_CACHE_PASS" }}'

          redisExec:
            host: '{{ requiredEnv "REDIS_HOST" }}'
            port: '{{ requiredEnv "REDIS_PORT" }}'
            tls: '{{ requiredEnv "REDIS_TLS" }}'
            pass: '{{ requiredEnv "REDIS_PASS" }}'
