repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: klicker-v2-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: ../charts/klicker-uzh-v2
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values.yaml
      - appSecret: '{{ requiredEnv "APP_SECRET" }}'

        frontendPWA:
          replicaCount: 3
          image:
            tag: v2.0.0-alpha.91

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN_PWA" }}'

        frontendManage:
          replicaCount: 1
          image:
            tag: v2.0.0-alpha.91

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN_MANAGE" }}'

        backendGraphql:
          replicaCount: 3
          image:
            tag: v2.0.0-alpha.91

          apiDomain: '{{ requiredEnv "API_DOMAIN" }}'
          cookieDomain: '{{ requiredEnv "COOKIE_DOMAIN" }}'
          databaseUrl: '{{ requiredEnv "DATABASE_URL" }}'
          hiveToken: '{{ requiredEnv "HIVE_TOKEN" }}'

          redisCache:
            host: klicker-v2-prod-redis-master
            port: 6379
            tls: false
            pass: ''

          redisExec:
            host: '{{ requiredEnv "REDIS_HOST" }}'
            port: '{{ requiredEnv "REDIS_PORT" }}'
            tls: '{{ requiredEnv "REDIS_TLS" }}'
            pass: '{{ requiredEnv "REDIS_PASS" }}'

          sentryEnv: production
          sentryDSN: '{{ env "SENTRY_DSN" }}'
