releases:
  - name: klicker-v2-prod
    namespace: klicker-v2-prod
    createNamespace: true
    chart: ../charts/klicker-uzh-v2
    version: '{{ env "CHART_VERSION" | default "0.1.0" }}'
    installed: true
    kubeContext: klicker-k8scbfdbd7c
    values:
      - values.yaml
      - frontendPWA:
          image:
            tag: v2.0.0-alpha.30
        frontendManage:
          image:
            tag: v2.0.0-alpha.30
