apiVersion: v2
name: klicker-uzh-v2
description: A Helm chart for the KlickerUZH
type: application
version: 2.0.0-alpha.111
appVersion: v2.0.0-alpha.111
dependencies:
  - name: redis
    version: 17.1.7
    repository: https://charts.bitnami.com/bitnami
