apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret-backend-graphql
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.appSecret | quote }}
  DATABASE_URL: {{ .Values.backendGraphql.databaseUrl | quote }}
  REDIS_CACHE_PASS: {{ .Values.backendGraphql.redisCache.pass | quote }}
  REDIS_PASS: {{ .Values.backendGraphql.redisExec.pass | quote }}
